language: python
python:
  - "3.6"

os:
  - linux

cache:
    - directories:
        - /home/travis/build/halirutan/itkbuild
        - /home/travis/build/halirutan/itksource
        - /home/travis/build/halirutan/ANTsPy/ants/lib
        - /home/travis/build/halirutan/ANTsPy/build
        - /usr/local

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      CMAKE_INSTALLER=install-cmake.sh && \
        curl -sSL https://cmake.org/files/v3.11/cmake-3.11.3-Linux-x86_64.sh -o ${CMAKE_INSTALLER} && \
        chmod +x ${CMAKE_INSTALLER} && \
        sudo ./${CMAKE_INSTALLER} --prefix=/usr/local --skip-license
    fi
  - alias cmake=/usr/local/bin/cmake
  - export PATH=/usr/local/bin/cmake/bin:/usr/local/bin:${PATH}
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      echo "need cmake 3.12" && \
        brew update && \
        brew install ccache && \
        brew upgrade cmake && \
        export PATH="/usr/local/opt/ccache/libexec:$PATH"
    fi
  - pip3 install scipy==1.2 pandas numpy matplotlib sklearn statsmodels nibabel
  - pip3 install coveralls plotly webcolors scikit-image;
  - pip3 install setuptools wheel
  - cd ..
  - if [ ! -f /home/travis/build/ANTsX/itkbuild/ITKConfig.cmake ]; then bash ${TRAVIS_BUILD_DIR}/scripts/configure_ITK.sh; fi
  - temp=`find ./ -name "ITKConfig.cmake"`
  - echo $temp
  - cd ${TRAVIS_BUILD_DIR}
  - export ITK_DIR=`pwd`/itkbuild/
  - echo $ITK_DIR
  - echo `ls $ITK_DIR`

install:
  - python3 setup.py build_py
  - python3 setup.py sdist bdist_wheel
  - python3 setup.py install


deploy:
  provider: releases
  api_key: $GITHUB_ACCESS_TOKEN
  file_glob: true
  file: /home/travis/build/ANTsX/ANTsPy/dist/antspyx*.whl
  skip_cleanup: true
  on:
    tags: true

script: ./tests/run_tests_travis.sh

branches:
  only:
    - master
